spring:
    application:
        name: product-management
    datasource:
      url: jdbc:h2:file:~/shopdb
      username: sa
      password:
      driver-class-name: org.h2.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
    h2:
      console:
        enabled: true
        settings:
          web-allow-others: true

    jackson:
      serialization:
        fail-on-empty-beans: false
fixer:
  api:
    url: http://data.fixer.io/api/latest
    key: cfba39ed170814a3152a5ef28176f0c4